require conf/machine/raspberrypi4-64.conf

MACHINEOVERRIDES =. "tinytrek-hw:"

# Set up the default tune (architecture)
DEFAULTTUNE = "cortexa72"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += " \
    kernel-modules \
"

RPI_USE_U_BOOT = "1"
IMAGE_INSTALL:append = " kernel-image kernel-devicetree"
