# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-tt"
BBFILE_PATTERN_meta-tt = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-tt = "100"

LAYERDEPENDS_meta-tt = "core"
LAYERSERIES_COMPAT_meta-tt = "scarthgap"
