#!/usr/bin/env python3
"""
TinyTrek CTF fleet provisioning generator -- single source of truth.

Emits, for an 8-car fleet:
  fleet-table.csv              master table (authoritative)
  ttos-provision-carNN.conf    one provisioning file per car
  firmware-constants.h         per-car Data IDs + unlock codes for node firmware
  OPERATOR-SECRETS.md          console passwords in plaintext -- do NOT ship

Regenerating changes ALL values. Run once, commit the output, then treat
fleet-table.csv as authoritative. Do not hand-edit individual files.

Usage: python3 gen-fleet.py [outdir]
"""
import csv, crypt, secrets, sys, pathlib

N_CARS       = 8
WIFI_COUNTRY = "US"
CHANNELS     = [36, 40, 44, 48, 149, 153, 157, 161]   # non-DFS 5 GHz, one per car
TXPOWER_MBM  = 500

# Pivot: 45 deg. track 9.4375in, wheel dia 2.3125in, 200 full steps/rev.
# arc = (45/360)*2*pi*(track/2) = 3.7061in; steps = arc/(pi*dia)*200 = 102.03
PIVOT_STEPS  = 102


# ---- VIN (ISO 3779) --------------------------------------------------------
TRANS = {**{str(d): d for d in range(10)},
 'A':1,'B':2,'C':3,'D':4,'E':5,'F':6,'G':7,'H':8,
 'J':1,'K':2,'L':3,'M':4,'N':5,'P':7,'R':9,
 'S':2,'T':3,'U':4,'V':5,'W':6,'X':7,'Y':8,'Z':9}
WEIGHTS = [8,7,6,5,4,3,2,10,0,9,8,7,6,5,4,3,2]

def vin_check_digit(v17):
    return 'X' if (t := sum(TRANS[c]*WEIGHTS[i] for i,c in enumerate(v17)) % 11) == 10 else str(t)

def make_vin(seq):
    # WMI=TTK (fictional) | VDS=TREK1 | chk | year T=2026 | plant C | seq
    stem, tail = "TTKTREK1", f"TC{seq:06d}"
    vin = stem + vin_check_digit(stem + "0" + tail) + tail
    assert len(vin) == 17 and vin_check_digit(vin) == vin[8]
    return vin

# ---- codes / secrets -------------------------------------------------------
ALPHA = "23456789ABCDEFGHJKMNPQRSTVWXYZ"   # no 0/O/1/I/L -- these get retyped
WORDS = ["amber","basalt","cinder","dovetail","ember","fathom","gantry","harbor",
         "indigo","jetty","kestrel","lantern","marlin","nimbus","onyx","pylon",
         "quarry","ridge","sable","tundra","umbra","vellum","willow","zephyr"]

def unlock_code(ch):  return ch + ''.join(secrets.choice(ALPHA) for _ in range(7))
def data_id():        return secrets.randbelow(0xFFFE) + 1
def wifi_psk():       return "-".join(secrets.choice(WORDS) for _ in range(3)) + f"-{secrets.randbelow(100):02d}"
def console_pw():     return ''.join(secrets.choice(ALPHA) for _ in range(20))

def main(outdir):
    outdir.mkdir(parents=True, exist_ok=True)
    fleet_salt = secrets.token_hex(16)   # fleet-wide, NOT secret (ships in client JS)
    rows, secretsheet = [], []

    for car in range(1, N_CARS + 1):
        did_l = data_id()
        did_r = data_id()
        while did_r == did_l:
            did_r = data_id()
        pw = console_pw()
        rows.append({
            "car_id":       f"{car:02d}",
            "hostname":     f"ttos-car-{car:02d}",
            "wifi_ssid":    f"ttos-car-{car:02d}",
            "wifi_psk":     wifi_psk(),
            "wifi_channel": CHANNELS[(car-1) % len(CHANNELS)],
            "vin":          make_vin(car),
            "ecu_serial":   f"TT-ECU-{car:02d}-{secrets.token_hex(4).upper()}",
            "dataid_l":     f"0x{did_l:04X}",
            "dataid_r":     f"0x{did_r:04X}",
            "code_c1":      unlock_code("1"),
            "code_c2":      unlock_code("2"),
            "code_c3":      unlock_code("3"),
            "console_hash": crypt.crypt(pw, crypt.mksalt(crypt.METHOD_SHA512)),
        })
        secretsheet.append((f"{car:02d}", pw))

    with (outdir/"fleet-table.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)

    for r in rows:
        (outdir/f"ttos-provision-car{r['car_id']}.conf").write_text(f"""# TinyTrek CTF provisioning -- car {r['car_id']}
# Generated by gen-fleet.py. Do not hand-edit; regenerate from fleet-table.csv.
# Consumed and shredded on first boot.

TTOS_HOSTNAME={r['hostname']}
TTOS_CAR_ID={r['car_id']}
TTOS_WIFI_SSID={r['wifi_ssid']}
TTOS_WIFI_PSK={r['wifi_psk']}
TTOS_WIFI_COUNTRY={WIFI_COUNTRY}
TTOS_WIFI_CHANNEL={r['wifi_channel']}
TTOS_WIFI_TXPOWER_MBM={TXPOWER_MBM}
TTOS_CONSOLE_PW_HASH={r['console_hash']}

# --- challenge provisioning ---
# Not secret: served over the diagnostic bus by design.
TTOS_VIN={r['vin']}
TTOS_ECU_SERIAL={r['ecu_serial']}
# Not secret: ships in client JS. Provisioned so it can rotate without a rebuild.
TTOS_FLEET_SALT={fleet_salt}
# SECRET: never transmitted. Recovering these is Challenge 3.
TTOS_DATAID_L={r['dataid_l']}
TTOS_DATAID_R={r['dataid_r']}
# SECRET: per-car unlock codes. Panel validates against this car only.
TTOS_CODE_C1={r['code_c1']}
TTOS_CODE_C2={r['code_c2']}
TTOS_CODE_C3={r['code_c3']}
""")

    fw = ["// Generated by gen-fleet.py -- do not hand-edit.",
          "// Define TTOS_CAR_NN at build time for the car being flashed.",
          "#pragma once", "",
          f"#define TTOS_PIVOT_STEPS  {PIVOT_STEPS}   // 45 deg in-place pivot", ""]
    for r in rows:
        fw += [f"#ifdef TTOS_CAR_{r['car_id']}",
               f"  #define TTOS_DATAID_L   {r['dataid_l']}",
               f"  #define TTOS_DATAID_R   {r['dataid_r']}",
               f'  #define TTOS_CODE_C2    "{r["code_c2"]}"',
               f'  #define TTOS_CODE_C3    "{r["code_c3"]}"',
               "#endif", ""]
    (outdir/"firmware-constants.h").write_text("\n".join(fw))


    op = ["# OPERATOR SECRETS -- DO NOT SHIP, DO NOT PRINT FOR THE TABLE", "",
          "Serial console passwords, plaintext. The cars store only the sha512crypt hash.",
          "Keep this off the competition floor.", "",
          "| Car | Console password (user `ttos`) |", "|---|---|"]
    for cid, pw in secretsheet:
        op.append(f"| {cid} | `{pw}` |")
    op += ["", f"Fleet salt: `{fleet_salt}`", ""]
    (outdir/"OPERATOR-SECRETS.md").write_text("\n".join(op))

    print(f"Generated {N_CARS} cars in {outdir}")
    print(f"  pivot steps: {PIVOT_STEPS}   fleet salt: {fleet_salt}")

if __name__ == "__main__":
    main(pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "out"))
