#!/usr/bin/env python3
"""
Render per-car provisioning files and the judge packet FROM fleet-table.csv.

This is NOT gen-fleet.py. gen-fleet.py *generates* random values and re-running it
changes every Data ID, unlock code, PSK and console password -- including ones
already written into firmware-constants.h and flashed to nodes. This script is
purely deterministic: it reads the authoritative fleet-table.csv and re-emits the
derived artifacts byte-for-byte. Safe to run any number of times.

Use it when ttos-provision-carNN.conf or judge-packet.md are missing or need to be
re-rendered after a template change. Never to mint new values.

Also note: gen-fleet.py imports `crypt`, removed from the stdlib in Python 3.13
(PEP 594). It will NOT run on arcana (3.14). This script needs no crypt -- the
sha512crypt hashes are already in the CSV.

Usage: python3 render-fleet.py [outdir]     (default: this directory)
"""
import csv, pathlib, sys

# Fleet-wide, NOT secret -- it ships in the dashboard's client JS (brief §5.4).
# Recorded in OPERATOR-SECRETS.md by the original gen-fleet.py run.
FLEET_SALT = "dd1b35d820f614e9c94f6a0e4f34cbc3"

WIFI_COUNTRY = "US"
TXPOWER_MBM = 500

SUBMISSION_FLAGS = {
    "C1": "FLAG[PIVOT_PIVOT_PIVOOOT]",
    "C2": "FLAG[STRAIGHT_OUTTA_GATEWAY]",
    "C3": "FLAG[THE_CALL_IS_COMING_FROM_INSIDE_THE_CAR]",
}


def car_conf(r):
    return f"""# TinyTrek CTF provisioning -- car {r['car_id']}
# Generated by gen-fleet.py. Do not hand-edit; regenerate from fleet-table.csv.
# Consumed and shredded on first boot.

TTOS_HOSTNAME={r['hostname']}
TTOS_CAR_ID={r['car_id']}
TTOS_WIFI_SSID={r['wifi_ssid']}
TTOS_WIFI_PSK={r['wifi_psk']}
TTOS_WIFI_COUNTRY={WIFI_COUNTRY}
TTOS_WIFI_CHANNEL={r['wifi_channel']}
TTOS_WIFI_TXPOWER_MBM={TXPOWER_MBM}
TTOS_CONSOLE_PW_HASH={r['console_hash']}

# --- challenge provisioning ---
# Not secret: served over the diagnostic bus by design.
TTOS_VIN={r['vin']}
TTOS_ECU_SERIAL={r['ecu_serial']}
# Not secret: ships in client JS. Provisioned so it can rotate without a rebuild.
TTOS_FLEET_SALT={FLEET_SALT}
# SECRET: never transmitted. Recovering these is Challenge 3.
TTOS_DATAID_L={r['dataid_l']}
TTOS_DATAID_R={r['dataid_r']}
# SECRET: per-car unlock codes. Panel validates against this car only.
TTOS_CODE_C1={r['code_c1']}
TTOS_CODE_C2={r['code_c2']}
TTOS_CODE_C3={r['code_c3']}
"""


def judge_packet(rows):
    jp = ["# Judge packet -- TinyTrek CTF", "",
          "Contestants capture a **per-car unlock code** from the vehicle and paste it into",
          "that car's control panel. The panel validates it and reveals the **static flag**",
          "to submit to CTFd.", "",
          "**If a panel is unreachable:** verify the contestant's per-car code below and hand",
          "out the matching FLAG string directly.", "",
          "## Static submission flags (CTFd)", ""]
    for k, v in SUBMISSION_FLAGS.items():
        jp.append(f"- **{k}**: `{v}`")
    jp += ["", "## Per-car unlock codes", "",
           "| Car | Hostname | Ch | C1 | C2 | C3 |", "|---|---|---|---|---|---|"]
    for r in rows:
        jp.append(f"| {r['car_id']} | {r['hostname']} | {r['wifi_channel']} | "
                  f"`{r['code_c1']}` | `{r['code_c2']}` | `{r['code_c3']}` |")
    jp += ["", "## WiFi (printed on each car's placard)", "",
           "| Car | SSID | PSK |", "|---|---|---|"]
    for r in rows:
        jp.append(f"| {r['car_id']} | `{r['wifi_ssid']}` | `{r['wifi_psk']}` |")
    jp += ["", "## Vehicle identity (for debugging a car claimed broken)", "",
           "| Car | VIN | ECU serial | DataID L | DataID R |", "|---|---|---|---|---|"]
    for r in rows:
        jp.append(f"| {r['car_id']} | `{r['vin']}` | `{r['ecu_serial']}` | "
                  f"`{r['dataid_l']}` | `{r['dataid_r']}` |")
    jp += ["", f"Fleet salt (not secret, ships in client JS): `{FLEET_SALT}`", "",
           "## Common contestant problems", "",
           "| Symptom | Cause |",
           "|---|---|",
           "| Nothing but errors on the tap | Classic-only adapter on an FD bus. Check the adapter before suspecting the car |",
           "| No traffic at all | The diagnostic bus is silent by design. They must send a request first |",
           "| Interface won't come up | FD data bitrate not set. The exact `ip link` line is on the placard |",
           "| Dashboard won't load | Chrome force-upgrades port 80 to HTTPS. Use Safari or Firefox |",
           "| Solved but no flag appeared | Station fault, not contestant error. Reset the car |",
           ""]
    return "\n".join(jp)


def main(outdir):
    here = pathlib.Path(__file__).resolve().parent
    with (here / "fleet-table.csv").open(newline="") as f:
        rows = list(csv.DictReader(f))
    outdir.mkdir(parents=True, exist_ok=True)
    for r in rows:
        # Per-car file under its own name, for reading and diffing.
        (outdir / f"ttos-provision-car{r['car_id']}.conf").write_text(car_conf(r))
        # AND a flash-ready copy under the name the car actually looks for.
        #
        # ttos-provision.sh only checks /boot/firmware/ttos-provision.conf and
        # /boot/ttos-provision.conf. A file dropped under any other name is not
        # found, the car silently enters FACTORY mode with an open TTOS-TEST AP,
        # and every downstream symptom looks like something else. Requiring a
        # rename during flashing is a trap; one directory per car removes it.
        flash = outdir / "flash" / f"car-{r['car_id']}"
        flash.mkdir(parents=True, exist_ok=True)
        (flash / "ttos-provision.conf").write_text(car_conf(r))
    (outdir / "judge-packet.md").write_text(judge_packet(rows))
    print(f"Rendered {len(rows)} car configs + judge-packet.md in {outdir}")
    print(f"  fleet salt: {FLEET_SALT}  (deterministic -- no values were generated)")


if __name__ == "__main__":
    main(pathlib.Path(sys.argv[1]) if len(sys.argv) > 1
         else pathlib.Path(__file__).resolve().parent)
