#!/usr/bin/env python3
"""
Render the per-car provisioning files FROM fleet-table.csv.

It used to also emit judge-packet.md. That was dropped 2026-08-04: it had gone stale
in a way that mattered -- it listed per-car unlock codes after the fleet went uniform,
and it named an exact Data ID when a correct Challenge 3 solve recovers a 256-member
equivalence class and cannot identify the true value. The judging path is /api/judge
on the car, which is car-level and server-side; the CTFd submission flags are the
SUBMISSION_FLAGS constant below.

This is NOT gen-fleet.py. gen-fleet.py *generates* random values and re-running it
changes every Data ID, unlock code, PSK and console password -- including ones
already written into firmware-constants.h and flashed to nodes. This script is
purely deterministic: it reads the authoritative fleet-table.csv and re-emits the
derived artifacts byte-for-byte. Safe to run any number of times.

Use it when the per-car provisioning files are missing or need re-rendering after a
template change. Never to mint new values.

Also note: gen-fleet.py imports `crypt`, removed from the stdlib in Python 3.13
(PEP 594). It will NOT run on arcana (3.14). This script needs no crypt -- the
sha512crypt hashes are already in the CSV.

Usage: python3 render-fleet.py [outdir]     (default: this directory)
"""
import csv, pathlib, sys

# Fleet-wide, NOT secret -- it ships in the dashboard's client JS (brief §5.4).
# Recorded in OPERATOR-SECRETS.md by the original gen-fleet.py run.
FLEET_SALT = "dd1b35d820f614e9c94f6a0e4f34cbc3"

WIFI_COUNTRY = "US"
TXPOWER_MBM = 500

# Operator SSH key, installed into ttos@car:~/.ssh/authorized_keys on first boot.
#
# WHY THIS IS HERE: a fresh card wipes the rootfs, so the key installed on the
# previous card is gone with it. Every bench script uses `ssh -o BatchMode=yes`
# (key auth, no prompt), so without this a reflashed car is unreachable to the
# whole harness until someone hand-copies a key -- eight times, and again after
# every reimage. ttos-provision has always supported TTOS_SSH_AUTHORIZED_KEY; the
# generator simply never emitted it.
#
# Empty string = omit the line entirely, which is the right default for a car that
# is going on a competition floor. Set it for bench and staging cars.
#
# NOT A SECRET: it is a public key. It does grant console access to whoever holds
# the matching private key, so do not ship a build machine's key on an event car.
OPERATOR_SSH_KEY = ""

_KEY_PATH = pathlib.Path.home() / ".ssh" / "id_ed25519.pub"
if not OPERATOR_SSH_KEY and _KEY_PATH.exists():
    OPERATOR_SSH_KEY = _KEY_PATH.read_text().strip()

SUBMISSION_FLAGS = {
    "C1": "FLAG[PIVOT_PIVOT_PIVOOOT]",
    "C2": "FLAG[STRAIGHT_OUTTA_GATEWAY]",
    "C3": "FLAG[THE_CALL_IS_COMING_FROM_INSIDE_THE_CAR]",
}


def _ssh_line(r):
    """The authorized-key line, or a comment saying why there is none."""
    if not OPERATOR_SSH_KEY:
        return ("# TTOS_SSH_AUTHORIZED_KEY absent: this car will accept only console-password\n"
                "# SSH. Bench scripts using BatchMode=yes will NOT be able to reach it.")
    return f"TTOS_SSH_AUTHORIZED_KEY={OPERATOR_SSH_KEY}"


def car_conf(r):
    return f"""# TinyTrek CTF provisioning -- car {r['car_id']}
# Generated by gen-fleet.py. Do not hand-edit; regenerate from fleet-table.csv.
# Consumed and shredded on first boot.

TTOS_HOSTNAME={r['hostname']}
TTOS_CAR_ID={r['car_id']}
TTOS_WIFI_SSID={r['wifi_ssid']}
TTOS_WIFI_PSK={r['wifi_psk']}
TTOS_WIFI_COUNTRY={WIFI_COUNTRY}
TTOS_WIFI_CHANNEL={r['wifi_channel']}
TTOS_WIFI_TXPOWER_MBM={TXPOWER_MBM}
TTOS_CONSOLE_PW_HASH={r['console_hash']}
{_ssh_line(r)}
# --- challenge provisioning ---
# Not secret: served over the diagnostic bus by design.
TTOS_VIN={r['vin']}
TTOS_ECU_SERIAL={r['ecu_serial']}
# Not secret: ships in client JS. Provisioned so it can rotate without a rebuild.
TTOS_FLEET_SALT={FLEET_SALT}
# SECRET: never transmitted. Recovering these is Challenge 3.
TTOS_DATAID_L={r['dataid_l']}
TTOS_DATAID_R={r['dataid_r']}
# SECRET: per-car unlock codes. Panel validates against this car only.
TTOS_CODE_C1={r['code_c1']}
TTOS_CODE_C2={r['code_c2']}
TTOS_CODE_C3={r['code_c3']}
"""


def main(outdir):
    here = pathlib.Path(__file__).resolve().parent
    with (here / "fleet-table.csv").open(newline="") as f:
        rows = list(csv.DictReader(f))
    outdir.mkdir(parents=True, exist_ok=True)
    for r in rows:
        # Per-car file under its own name, for reading and diffing.
        (outdir / f"ttos-provision-car{r['car_id']}.conf").write_text(car_conf(r))
        # AND a flash-ready copy under the name the car actually looks for.
        #
        # ttos-provision.sh only checks /boot/firmware/ttos-provision.conf and
        # /boot/ttos-provision.conf. A file dropped under any other name is not
        # found, the car silently enters FACTORY mode with an open TTOS-TEST AP,
        # and every downstream symptom looks like something else. Requiring a
        # rename during flashing is a trap; one directory per car removes it.
        flash = outdir / "flash" / f"car-{r['car_id']}"
        flash.mkdir(parents=True, exist_ok=True)
        (flash / "ttos-provision.conf").write_text(car_conf(r))
    print(f"Rendered {len(rows)} car configs in {outdir}")
    print(f"  fleet salt: {FLEET_SALT}  (deterministic -- no values were generated)")


if __name__ == "__main__":
    main(pathlib.Path(sys.argv[1]) if len(sys.argv) > 1
         else pathlib.Path(__file__).resolve().parent)
